### ISSUE TITLE
Using PostProcessorRegistration

### ISSUE THREAD

**Issue by asraa** [google/libprotobuf-mutator#142]
Hi, 

I'm trying to use `PostProcessorRegistration` for one of our fuzz tests following the example here:
https://github.com/google/libprotobuf-mutator/blob/6a6820c71cd180f3756c24e05ff0a7675675a00a/examples/libfuzzer/libfuzzer_example.cc#L22

It seems like the function I register is never executed. I'm trying to clear a field that libfuzzer populates in my protobuf because we don't implement functionality for it (and otherwise it reaches a panic assert). I could always do this manually, but I figured I should try out this new functionality. 

I've registered the function, which clears the comprehension expression field if it has it. Later in the test, I printed out the input protobuf, and it still keeps the comprehension expression field. Is the`PostProcessorRegistration` meant to mutate the protobuf inputs?

My test looks something like:

```
DEFINE_PROTO_FUZZER(const test::extensions::filters::common::expr::EvaluatorTestCase& input) {
  static PostProcessorRegistration reg = {
    [](test::extensions::filters::common::expr::EvaluatorTestCase* input, unsigned int /*seed*/) {
        if (input->expression().expr_kind_case() ==
            google::api::expr::v1alpha1::Expr::kComprehensionExpr) {
          input->mutable_expression()->clear_expr_kind();
        }
      }};

  // Create builder without constant folding.
  static Expr::BuilderPtr builder = Expr::createBuilder(nullptr);

  try {
    // Validate that the input has an expression.
    TestUtility::validate(input);
    ENVOY_LOG_MISC(info, "PROTOBUF {}", input.expression().DebugString());

    // Create the CEL expression.
    Expr::ExpressionPtr expr = Expr::createExpression(*builder, input.expression());

    // Create the headers and stream_info to test against.
    TestStreamInfo stream_info = makeStreamInfo(input.stream_info());
    Http::TestHeaderMapImpl request_headers = Fuzz::fromHeaders(input.request_headers());
    Http::TestHeaderMapImpl response_headers = Fuzz::fromHeaders(input.response_headers());
    Http::TestHeaderMapImpl response_trailers = Fuzz::fromHeaders(input.trailers());

    // Evaluate the CEL expression.
    Protobuf::Arena arena;
    Expr::evaluate(*expr, nullptr, stream_info, &request_headers, &response_headers,
                   &response_trailers);
    arena.Reset();
  } catch (const EnvoyException& e) {
    ENVOY_LOG_MISC(debug, "EnvoyException: {}", e.what());
  }
}
```

**Comment by vitalybuka** [comment]
This one should apply to mutation. Still if you already have a corpus with this field, it will be passed into your fuzzer. Is this that case?

**Comment by asraa** [comment]
Yes! I see. I added that testcase to validate it was scrubbing that away.

Thank you so much, I understand now. It applies when producing inputs via mutations.
