### ISSUE TITLE
Custom semantic mutators

### ISSUE THREAD

**Issue by bshastry** [google/libprotobuf-mutator#144]
Hello,

Would it be possible to permit overriding the mutate implementation of libprotobuf-mutator? Use case is semantic mutation.

Example:

input
```
ifstmt {
  condition {
       varref {
          id: "x"
       }
  }
...
}
```

converts to `if (x) { do_something }`. On this, I would like to define a mutation that flips the condition to `if !x { do something}`, the mutated protobuf input being

```
ifstmt {
   condition {
      not {
        varref {
           id: "x"
        }
     }
  }
}
```

**Comment by vitalybuka** [comment]
Not sure if I understand the question.
Still maybe PostProcessorRegistration can solve your problem?
You can use it to tweak message as you like.

https://github.com/google/libprotobuf-mutator/blob/dd89da92b59b1714bab6e2a135093948a1cf1c6a/examples/libfuzzer/libfuzzer_example.cc#L23

**Comment by bshastry** [comment]
Thanks for your input. Yeah, I came to the same conclusion :-)

**Comment by bshastry** [comment]
Do you happen to know about this

```
libprotobuf-mutator/src/mutator.cc:471:43: runtime error: member call on address 0x000007da9f40 which  does not point to an object of type 'google::protobuf::Message'
```

from 

https://github.com/google/libprotobuf-mutator/blob/dd89da92b59b1714bab6e2a135093948a1cf1c6a/src/mutator.cc#L471

**Comment by vitalybuka** [comment]
can you share a reproducer?

**Comment by bshastry** [comment]
I think this may be an issue with my postprocessor callback. I took a look at the linked example, where you add an optional field in a message

https://github.com/google/libprotobuf-mutator/blob/dd89da92b59b1714bab6e2a135093948a1cf1c6a/examples/libfuzzer/libfuzzer_example.cc#L27

Is there a slightly more advanced example where the field is itself a message that you need to create and add to the existing message passed via the callback?

**Comment by bshastry** [comment]
Closing because the original question has been addressed.
