### ISSUE TITLE
Dictionaries with LPM

### ISSUE THREAD

**Issue by asraa** [google/libprotobuf-mutator#145]
Hi, I had a quick question about using dictionary files and LPM. I am fuzzing a target that consumes a format string along with some other protobuf data. I'd like to include common strings that we use in format strings to populate the format string field in the protobuf. If I define a .dict field like I do for ordinary fuzzers, how will LPM interpret the data in the dictionary? Will it use it to populate string fields or will it use try to deserialize the data in the dictionary into the protobuf?

Thank you!

**Comment by vitalybuka** [comment]
it should use it to populate strings.
LMP calls libfuzzer to mutate string, and libfuzzer suppose to use dictionary.
Could you try this? If it does not happen, then it's probably a bug in libfuzzer.

**Comment by asraa** [comment]
Just wanted to close this out since I've verified it in my filter fuzzer. Thanks!
