### ISSUE TITLE
example for nested callback doesn't work

### ISSUE THREAD

**Issue by pdknsk** [google/libprotobuf-mutator#164]
Fails with no matching constructor for initialization of `PostProcessorRegistration<MyMessageType>`.

Whereas this appears to work.
```C++
static protobuf_mutator::libfuzzer::PostProcessorRegistration<MyMessageType::Nested> reg_nested = {
  [](MyMessageType::Nested* message, unsigned int seed) {
  }};
```

**Comment by vitalybuka** [comment]
Can you share more details?
It compiles here https://travis-ci.org/google/libprotobuf-mutator

**Comment by pdknsk** [comment]
Which example is that? I only noticed [libfuzzer_bin_example.cc](https://github.com/google/libprotobuf-mutator/blob/master/examples/libfuzzer/libfuzzer_bin_example.cc) which doesn't use a nested message in the callback. I meant the example from the `README`.
