### ISSUE TITLE
AllowUnknownField ignores SetRecursionLimit

### ISSUE THREAD

**Issue by vitalybuka** [google/libprotobuf-mutator#172]

**Comment by vitalybuka** [comment]
Hey @nareddyt, would you mind to take a look at proto implementation?
I suspect it's something trivial.

**Comment by nareddyt** [comment]
Sure

**Comment by nareddyt** [comment]
I am able to reproduce the problem. I'll look into how easy it is to fix...

**Comment by nareddyt** [comment]
Made in the change in google3, just waiting for it to propagate up to the protobuf Github repository before reverting #173
