### ISSUE TITLE
Question about the expat example 

### ISSUE THREAD

**Issue by ysuperGit** [google/libprotobuf-mutator#189]
Why does the expat_example.cc file in the expat folder still run without the main function and there is no error when compiling?

**Comment by vitalybuka** [comment]
main() is in LLVM libFuzzer https://llvm.org/docs/LibFuzzer.html
expat_example.cc exports functions which called by libFuzzer

**Comment by ysuperGit** [comment]
> main() is in LLVM libFuzzer https://llvm.org/docs/LibFuzzer.html
> expat_example.cc exports functions which called by libFuzzer

Thank you for your help. 
I think it is necessary for me to understand libfuzzer first
