### ISSUE TITLE
can I mutate two messages at once?

### ISSUE THREAD

**Issue by aibarito** [google/libprotobuf-mutator#190]
Hello! I have a question. Can I somehow mutate two different messages and write them to two different topics inside of one DEFINE_PROTO_FUZZER() body?
I need it because I want to fuzz a program that is subscribed to several topics, so I want to put the whole program inside a DEFINE_PROTO_FUZZER() body to use the code coverage feature of libfuzzer.

**Comment by aibarito** [comment]
Oh, I got an idea! I can create a message that has another messages as fields and then pass this created message is it right

**Comment by vitalybuka** [comment]
You can create a new message with two nested field of message types you need.
