### ISSUE TITLE
Next release after 1.0?

### ISSUE THREAD

**Issue by hartwork** [google/libprotobuf-mutator#211]
Hi!

The latest release `1.0` is near two years old. Some distros [have packaged some off-release Git commit snapshots](https://repology.org/project/libprotobuf-mutator/versions), and no two distros have the same version of libprotobuf-mutator packaged today. It would rock, if the [post-1.0 commits](https://github.com/google/libprotobuf-mutator/compare/v1.0...master) could be cast into a new release — e.g. `1.1` — to cleanly get the post-1.0 fixes to everyone midterm. Any chance?

Thanks and best, Sebastian

**Comment by vitalybuka** [comment]
Sorry, our internal use is to compile from sources.
Done! https://github.com/google/libprotobuf-mutator/releases

**Comment by hartwork** [comment]
Thank you!
