### ISSUE TITLE
Ninja check failed

### ISSUE THREAD

**Issue by lipeng28** [google/libprotobuf-mutator#228]
Hi There
I am using the following command to build the libprotobuf-mutator:
cmake .. -GNinja -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_BUILD_TYPE=Debug -DLIB_PROTO_MUTATOR_DOWNLOAD_PROTOBUF=ON
ninja check

I used the clang 9.0, and encountered the following problems, do you think it is caused by older version of clang?

In file included from /home/peli/clang/libprotobuf-mutator/src/binary_format.cc:15:
In file included from /home/peli/clang/libprotobuf-mutator/src/binary_format.h:20:
In file included from /home/peli/clang/libprotobuf-mutator/port/protobuf.h:20:
In file included from /home/peli/clang/libprotobuf-mutator/build/external.protobuf/include/google/protobuf/any.pb.h:11:
/home/peli/clang/libprotobuf-mutator/build/external.protobuf/include/google/protobuf/port_def.inc:996:32: error: unknown warning group '-Wdeprecated-enum-enum-conversion', ignored [-Werror,-Wunknown-warning-option]
#pragma clang diagnostic error "-Wdeprecated-enum-enum-conversion"

In file included from /home/peli/clang/libprotobuf-mutator/src/mutator.cc:15:
In file included from /home/peli/clang/libprotobuf-mutator/src/mutator.h:28:
In file included from /home/peli/clang/libprotobuf-mutator/port/protobuf.h:20:
In file included from /home/peli/clang/libprotobuf-mutator/build/external.protobuf/include/google/protobuf/any.pb.h:25:
In file included from /home/peli/clang/libprotobuf-mutator/build/external.protobuf/include/google/protobuf/arena.h:55:
In file included from /home/peli/clang/libprotobuf-mutator/build/external.protobuf/include/google/protobuf/thread_safe_arena.h:52:
/home/peli/clang/libprotobuf-mutator/build/external.protobuf/include/google/protobuf/port_def.inc:996:32: error: unknown warning group '-Wdeprecated-enum-enum-conversion', ignored [-Werror,-Wunknown-warning-option]
#pragma clang diagnostic error "-Wdeprecated-enum-enum-conversion"

Thanks 
Peng

**Comment by vitalybuka** [comment]
very likely
